//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Keysight.KtEL30000.Bridge {
[System.CodeDom.Compiler.GeneratedCode("swig","3.0")]

internal class KtEL30000StatusQuestionable : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal KtEL30000StatusQuestionable(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(KtEL30000StatusQuestionable obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~KtEL30000StatusQuestionable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          KtEL30000CppApiPINVOKE.delete_KtEL30000StatusQuestionable(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }


    public Keysight.KtEL30000.StatusQuestionableFlags EnableRegister
    {
        get { return GetEnableRegister(); }
        set { SetEnableRegister(value); }
    }

    public Keysight.KtEL30000.StatusQuestionableFlags NegativeTransitionFilter
    {
        get { return GetNegativeTransitionFilter(); }
        set { SetNegativeTransitionFilter(value); }
    }

    public Keysight.KtEL30000.StatusQuestionableFlags PositiveTransitionFilter
    {
        get { return GetPositiveTransitionFilter(); }
        set { SetPositiveTransitionFilter(value); }
    }

  public Keysight.KtEL30000.StatusQuestionableFlags ReadConditionRegister() {
    Keysight.KtEL30000.StatusQuestionableFlags ret = (Keysight.KtEL30000.StatusQuestionableFlags)KtEL30000CppApiPINVOKE.KtEL30000StatusQuestionable_ReadConditionRegister(swigCPtr);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Keysight.KtEL30000.StatusQuestionableFlags ReadEventRegister() {
    Keysight.KtEL30000.StatusQuestionableFlags ret = (Keysight.KtEL30000.StatusQuestionableFlags)KtEL30000CppApiPINVOKE.KtEL30000StatusQuestionable_ReadEventRegister(swigCPtr);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Keysight.KtEL30000.StatusQuestionableFlags GetEnableRegister() {
    Keysight.KtEL30000.StatusQuestionableFlags ret = (Keysight.KtEL30000.StatusQuestionableFlags)KtEL30000CppApiPINVOKE.KtEL30000StatusQuestionable_GetEnableRegister(swigCPtr);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetEnableRegister(Keysight.KtEL30000.StatusQuestionableFlags value) {
    KtEL30000CppApiPINVOKE.KtEL30000StatusQuestionable_SetEnableRegister(swigCPtr, (int)value);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public Keysight.KtEL30000.StatusQuestionableFlags GetNegativeTransitionFilter() {
    Keysight.KtEL30000.StatusQuestionableFlags ret = (Keysight.KtEL30000.StatusQuestionableFlags)KtEL30000CppApiPINVOKE.KtEL30000StatusQuestionable_GetNegativeTransitionFilter(swigCPtr);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetNegativeTransitionFilter(Keysight.KtEL30000.StatusQuestionableFlags value) {
    KtEL30000CppApiPINVOKE.KtEL30000StatusQuestionable_SetNegativeTransitionFilter(swigCPtr, (int)value);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public Keysight.KtEL30000.StatusQuestionableFlags GetPositiveTransitionFilter() {
    Keysight.KtEL30000.StatusQuestionableFlags ret = (Keysight.KtEL30000.StatusQuestionableFlags)KtEL30000CppApiPINVOKE.KtEL30000StatusQuestionable_GetPositiveTransitionFilter(swigCPtr);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetPositiveTransitionFilter(Keysight.KtEL30000.StatusQuestionableFlags value) {
    KtEL30000CppApiPINVOKE.KtEL30000StatusQuestionable_SetPositiveTransitionFilter(swigCPtr, (int)value);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
