//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Keysight.KtEL30000.Bridge {
[System.CodeDom.Compiler.GeneratedCode("swig","3.0")]

internal class KtEL30000OperationConstantPower : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal KtEL30000OperationConstantPower(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(KtEL30000OperationConstantPower obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~KtEL30000OperationConstantPower() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          KtEL30000CppApiPINVOKE.delete_KtEL30000OperationConstantPower(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

    public KtEL30000OperationConstantPowerProtection Protection_
    {
        get { return Protection(); }
    }
    public KtEL30000OperationConstantPowerSlew Slew_
    {
        get { return Slew(); }
    }
    public System.Double[] GetPower(string channelList)
    {
        var ret = default(System.Double[]);
        this.GetPower(channelList, ref ret);
        return ret;
    }
    public System.Double[] GetPower(Keysight.KtEL30000.MinMaxDefMode powerLevel, string channelList)
    {
        var ret = default(System.Double[]);
        this.GetPower(powerLevel, channelList, ref ret);
        return ret;
    }
    public Keysight.KtEL30000.PowerMode[] GetMode(string channelList)
    {
        var ret = default(Keysight.KtEL30000.PowerMode[]);
        this.GetMode(channelList, ref ret);
        return ret;
    }
    public System.Double[] GetTriggerLevel(string channelList)
    {
        var ret = default(System.Double[]);
        this.GetTriggerLevel(channelList, ref ret);
        return ret;
    }
    public System.Double[] GetTriggerLevel(Keysight.KtEL30000.MinMaxDefMode triggerLevel, string channelList)
    {
        var ret = default(System.Double[]);
        this.GetTriggerLevel(triggerLevel, channelList, ref ret);
        return ret;
    }
    public System.Double[] GetPowerRange(string channelList)
    {
        var ret = default(System.Double[]);
        this.GetPowerRange(channelList, ref ret);
        return ret;
    }
    public System.Double[] GetPowerRange(Keysight.KtEL30000.MinMaxDefMode range, string channelList)
    {
        var ret = default(System.Double[]);
        this.GetPowerRange(range, channelList, ref ret);
        return ret;
    }

  public void GetPower(string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantPower_GetPower__SWIG_0(swigCPtr, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void GetPower(Keysight.KtEL30000.MinMaxDefMode powerLevel, string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantPower_GetPower__SWIG_1(swigCPtr, (int)powerLevel, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void GetMode(string channelList, ref Keysight.KtEL30000.PowerMode[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.EnumArrayMarshaler<Keysight.KtEL30000.PowerMode>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantPower_GetMode(swigCPtr, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void GetTriggerLevel(string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantPower_GetTriggerLevel__SWIG_0(swigCPtr, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void GetTriggerLevel(Keysight.KtEL30000.MinMaxDefMode triggerLevel, string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantPower_GetTriggerLevel__SWIG_1(swigCPtr, (int)triggerLevel, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void SetPower(double powerLevel, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantPower_SetPower__SWIG_0(swigCPtr, powerLevel, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetPower(Keysight.KtEL30000.MinMaxDefMode powerLevel, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantPower_SetPower__SWIG_1(swigCPtr, (int)powerLevel, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetMode(Keysight.KtEL30000.PowerMode mode, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantPower_SetMode(swigCPtr, (int)mode, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetTriggerLevel(Keysight.KtEL30000.MinMaxDefMode triggerLevel, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantPower_SetTriggerLevel__SWIG_0(swigCPtr, (int)triggerLevel, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetTriggerLevel(double triggerLevel, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantPower_SetTriggerLevel__SWIG_1(swigCPtr, triggerLevel, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetPowerRange(double range, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantPower_SetPowerRange__SWIG_0(swigCPtr, range, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetPowerRange(Keysight.KtEL30000.MinMaxDefMode range, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantPower_SetPowerRange__SWIG_1(swigCPtr, (int)range, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetPowerRange(string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantPower_GetPowerRange__SWIG_0(swigCPtr, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void GetPowerRange(Keysight.KtEL30000.MinMaxDefMode range, string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantPower_GetPowerRange__SWIG_1(swigCPtr, (int)range, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public KtEL30000OperationConstantPowerProtection Protection() {
    global::System.IntPtr cPtr = KtEL30000CppApiPINVOKE.KtEL30000OperationConstantPower_Protection(swigCPtr);
    KtEL30000OperationConstantPowerProtection ret = (cPtr == global::System.IntPtr.Zero) ? null : new KtEL30000OperationConstantPowerProtection(cPtr, true);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public KtEL30000OperationConstantPowerSlew Slew() {
    global::System.IntPtr cPtr = KtEL30000CppApiPINVOKE.KtEL30000OperationConstantPower_Slew(swigCPtr);
    KtEL30000OperationConstantPowerSlew ret = (cPtr == global::System.IntPtr.Zero) ? null : new KtEL30000OperationConstantPowerSlew(cPtr, true);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
