//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Keysight.KtEL30000.Bridge {
[System.CodeDom.Compiler.GeneratedCode("swig","3.0")]

internal class KtEL30000OperationConstantVoltage : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal KtEL30000OperationConstantVoltage(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(KtEL30000OperationConstantVoltage obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~KtEL30000OperationConstantVoltage() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          KtEL30000CppApiPINVOKE.delete_KtEL30000OperationConstantVoltage(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

    public KtEL30000OperationConstantVoltageSlew Slew_
    {
        get { return Slew(); }
    }
    public System.Double[] GetVoltage(string channelList)
    {
        var ret = default(System.Double[]);
        this.GetVoltage(channelList, ref ret);
        return ret;
    }
    public System.Double[] GetVoltage(Keysight.KtEL30000.MinMaxDefMode levelValue, string channelList)
    {
        var ret = default(System.Double[]);
        this.GetVoltage(levelValue, channelList, ref ret);
        return ret;
    }
    public Keysight.KtEL30000.VoltageMode[] GetMode(string channelList)
    {
        var ret = default(Keysight.KtEL30000.VoltageMode[]);
        this.GetMode(channelList, ref ret);
        return ret;
    }
    public System.Double[] GetTriggerLevel(string channelList)
    {
        var ret = default(System.Double[]);
        this.GetTriggerLevel(channelList, ref ret);
        return ret;
    }
    public System.Double[] GetTriggerLevel(Keysight.KtEL30000.MinMaxDefMode levelValue, string channelList)
    {
        var ret = default(System.Double[]);
        this.GetTriggerLevel(levelValue, channelList, ref ret);
        return ret;
    }
    public System.Double[] GetCurrentLimit(Keysight.KtEL30000.MinMaxDefMode currentLimit, string channelList)
    {
        var ret = default(System.Double[]);
        this.GetCurrentLimit(currentLimit, channelList, ref ret);
        return ret;
    }
    public System.Double[] GetCurrentLimit(string channelList)
    {
        var ret = default(System.Double[]);
        this.GetCurrentLimit(channelList, ref ret);
        return ret;
    }
    public System.Double[] GetVoltageRange(Keysight.KtEL30000.MinMaxDefMode range, string channelList)
    {
        var ret = default(System.Double[]);
        this.GetVoltageRange(range, channelList, ref ret);
        return ret;
    }
    public System.Double[] GetVoltageRange(string channelList)
    {
        var ret = default(System.Double[]);
        this.GetVoltageRange(channelList, ref ret);
        return ret;
    }
    public Keysight.KtEL30000.SenseMode[] GetVoltageSensingMode(string channelList)
    {
        var ret = default(Keysight.KtEL30000.SenseMode[]);
        this.GetVoltageSensingMode(channelList, ref ret);
        return ret;
    }
    public System.Double[] GetInhibitVoltageTurnOnLevel(Keysight.KtEL30000.MinMaxDefMode inhibitVoltageTurnOnLevel, string channelList)
    {
        var ret = default(System.Double[]);
        this.GetInhibitVoltageTurnOnLevel(inhibitVoltageTurnOnLevel, channelList, ref ret);
        return ret;
    }
    public System.Double[] GetInhibitVoltageTurnOnLevel(string channelList)
    {
        var ret = default(System.Double[]);
        this.GetInhibitVoltageTurnOnLevel(channelList, ref ret);
        return ret;
    }
    public Keysight.KtEL30000.InhibitMode[] GetInhibitVoltageTurnOnMode(string channelList)
    {
        var ret = default(Keysight.KtEL30000.InhibitMode[]);
        this.GetInhibitVoltageTurnOnMode(channelList, ref ret);
        return ret;
    }

  public void GetVoltage(string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_GetVoltage__SWIG_0(swigCPtr, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void GetVoltage(Keysight.KtEL30000.MinMaxDefMode levelValue, string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_GetVoltage__SWIG_1(swigCPtr, (int)levelValue, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void GetMode(string channelList, ref Keysight.KtEL30000.VoltageMode[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.EnumArrayMarshaler<Keysight.KtEL30000.VoltageMode>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_GetMode(swigCPtr, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void GetTriggerLevel(string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_GetTriggerLevel__SWIG_0(swigCPtr, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void GetTriggerLevel(Keysight.KtEL30000.MinMaxDefMode levelValue, string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_GetTriggerLevel__SWIG_1(swigCPtr, (int)levelValue, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void SetVoltage(double voltageValue, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_SetVoltage__SWIG_0(swigCPtr, voltageValue, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetVoltage(Keysight.KtEL30000.MinMaxDefMode voltageValue, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_SetVoltage__SWIG_1(swigCPtr, (int)voltageValue, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetMode(Keysight.KtEL30000.VoltageMode mode, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_SetMode(swigCPtr, (int)mode, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetTriggerLevel(Keysight.KtEL30000.MinMaxDefMode triggerLevel, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_SetTriggerLevel__SWIG_0(swigCPtr, (int)triggerLevel, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetTriggerLevel(double triggerLevel, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_SetTriggerLevel__SWIG_1(swigCPtr, triggerLevel, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetCurrentLimit(Keysight.KtEL30000.MinMaxDefMode currentLimit, string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_GetCurrentLimit__SWIG_0(swigCPtr, (int)currentLimit, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void SetCurrentLimit(Keysight.KtEL30000.MinMaxDefMode currentLimit, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_SetCurrentLimit__SWIG_0(swigCPtr, (int)currentLimit, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetCurrentLimit(double currentLimit, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_SetCurrentLimit__SWIG_1(swigCPtr, currentLimit, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetCurrentLimit(string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_GetCurrentLimit__SWIG_1(swigCPtr, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void SetVoltageRange(double range, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_SetVoltageRange__SWIG_0(swigCPtr, range, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetVoltageRange(Keysight.KtEL30000.MinMaxDefMode range, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_SetVoltageRange__SWIG_1(swigCPtr, (int)range, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetVoltageRange(Keysight.KtEL30000.MinMaxDefMode range, string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_GetVoltageRange__SWIG_0(swigCPtr, (int)range, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void GetVoltageRange(string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_GetVoltageRange__SWIG_1(swigCPtr, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void GetVoltageSensingMode(string channelList, ref Keysight.KtEL30000.SenseMode[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.EnumArrayMarshaler<Keysight.KtEL30000.SenseMode>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_GetVoltageSensingMode(swigCPtr, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void SetVoltageSensingMode(Keysight.KtEL30000.SenseMode senseMode, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_SetVoltageSensingMode(swigCPtr, (int)senseMode, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetInhibitVoltageTurnOnLevel(Keysight.KtEL30000.MinMaxDefMode inhibitVoltageTurnOnLevel, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_SetInhibitVoltageTurnOnLevel__SWIG_0(swigCPtr, (int)inhibitVoltageTurnOnLevel, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetInhibitVoltageTurnOnLevel(Keysight.KtEL30000.MinMaxDefMode inhibitVoltageTurnOnLevel, string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_GetInhibitVoltageTurnOnLevel__SWIG_0(swigCPtr, (int)inhibitVoltageTurnOnLevel, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void SetInhibitVoltageTurnOnLevel(double inhibitVoltageTurnOnLevel, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_SetInhibitVoltageTurnOnLevel__SWIG_1(swigCPtr, inhibitVoltageTurnOnLevel, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetInhibitVoltageTurnOnLevel(string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_GetInhibitVoltageTurnOnLevel__SWIG_1(swigCPtr, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void SetInhibitVoltageTurnOnMode(Keysight.KtEL30000.InhibitMode inhibitVoltageTurnOnMode, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_SetInhibitVoltageTurnOnMode(swigCPtr, (int)inhibitVoltageTurnOnMode, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetInhibitVoltageTurnOnMode(string channelList, ref Keysight.KtEL30000.InhibitMode[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.EnumArrayMarshaler<Keysight.KtEL30000.InhibitMode>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_GetInhibitVoltageTurnOnMode(swigCPtr, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public KtEL30000OperationConstantVoltageSlew Slew() {
    global::System.IntPtr cPtr = KtEL30000CppApiPINVOKE.KtEL30000OperationConstantVoltage_Slew(swigCPtr);
    KtEL30000OperationConstantVoltageSlew ret = (cPtr == global::System.IntPtr.Zero) ? null : new KtEL30000OperationConstantVoltageSlew(cPtr, true);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
