//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Keysight.KtEL30000.Bridge {
[System.CodeDom.Compiler.GeneratedCode("swig","3.0")]

internal class KtEL30000OperationConstantCurrent : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal KtEL30000OperationConstantCurrent(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(KtEL30000OperationConstantCurrent obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~KtEL30000OperationConstantCurrent() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          KtEL30000CppApiPINVOKE.delete_KtEL30000OperationConstantCurrent(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

    public KtEL30000OperationConstantCurrentProtection Protection_
    {
        get { return Protection(); }
    }
    public KtEL30000OperationConstantCurrentSlew Slew_
    {
        get { return Slew(); }
    }
    public System.Double[] GetCurrent(string channelList)
    {
        var ret = default(System.Double[]);
        this.GetCurrent(channelList, ref ret);
        return ret;
    }
    public System.Double[] GetTriggerLevel(Keysight.KtEL30000.MinMaxDefMode triggerLevel, string channelList)
    {
        var ret = default(System.Double[]);
        this.GetTriggerLevel(triggerLevel, channelList, ref ret);
        return ret;
    }
    public System.Double[] GetTriggerLevel(string channelList)
    {
        var ret = default(System.Double[]);
        this.GetTriggerLevel(channelList, ref ret);
        return ret;
    }
    public Keysight.KtEL30000.CurrentMode[] GetMode(string channelList)
    {
        var ret = default(Keysight.KtEL30000.CurrentMode[]);
        this.GetMode(channelList, ref ret);
        return ret;
    }
    public System.Double[] GetCurrent(Keysight.KtEL30000.MinMaxDefMode currentLevel, string channelList)
    {
        var ret = default(System.Double[]);
        this.GetCurrent(currentLevel, channelList, ref ret);
        return ret;
    }
    public System.Double[] GetCurrentRange(Keysight.KtEL30000.MinMaxDefMode range, string channelList)
    {
        var ret = default(System.Double[]);
        this.GetCurrentRange(range, channelList, ref ret);
        return ret;
    }
    public System.Double[] GetCurrentRange(string channelList)
    {
        var ret = default(System.Double[]);
        this.GetCurrentRange(channelList, ref ret);
        return ret;
    }

  public void GetCurrent(string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantCurrent_GetCurrent__SWIG_0(swigCPtr, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void SetTriggerLevel(Keysight.KtEL30000.MinMaxDefMode triggerLevel, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantCurrent_SetTriggerLevel__SWIG_0(swigCPtr, (int)triggerLevel, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetTriggerLevel(Keysight.KtEL30000.MinMaxDefMode triggerLevel, string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantCurrent_GetTriggerLevel__SWIG_0(swigCPtr, (int)triggerLevel, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void GetTriggerLevel(string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantCurrent_GetTriggerLevel__SWIG_1(swigCPtr, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void SetTriggerLevel(double triggerLevel, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantCurrent_SetTriggerLevel__SWIG_1(swigCPtr, triggerLevel, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetMode(Keysight.KtEL30000.CurrentMode mode, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantCurrent_SetMode(swigCPtr, (int)mode, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetMode(string channelList, ref Keysight.KtEL30000.CurrentMode[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.EnumArrayMarshaler<Keysight.KtEL30000.CurrentMode>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantCurrent_GetMode(swigCPtr, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void GetCurrent(Keysight.KtEL30000.MinMaxDefMode currentLevel, string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantCurrent_GetCurrent__SWIG_1(swigCPtr, (int)currentLevel, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void SetCurrent(Keysight.KtEL30000.MinMaxDefMode currentValue, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantCurrent_SetCurrent__SWIG_0(swigCPtr, (int)currentValue, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetCurrent(double currentValue, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantCurrent_SetCurrent__SWIG_1(swigCPtr, currentValue, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetCurrentRange(Keysight.KtEL30000.MinMaxDefMode range, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantCurrent_SetCurrentRange__SWIG_0(swigCPtr, (int)range, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetCurrentRange(Keysight.KtEL30000.MinMaxDefMode range, string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantCurrent_GetCurrentRange__SWIG_0(swigCPtr, (int)range, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void GetCurrentRange(string channelList, ref System.Double[] INOUT) {
    var marshaler_INOUT = new Keysight.ApiCoreLibraries.BlittableArrayMarshaler<System.Double>();
    var marshalBuffer_INOUT = new Keysight.ApiCoreLibraries.MarshalBuffer(marshaler_INOUT.BufferSize);
    marshaler_INOUT.CSharpToBytes(INOUT, marshalBuffer_INOUT);
    try {
      KtEL30000CppApiPINVOKE.KtEL30000OperationConstantCurrent_GetCurrentRange__SWIG_1(swigCPtr, channelList, marshalBuffer_INOUT.PinnedBytes);
      if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    } finally {
    marshalBuffer_INOUT.ResetOffset();
    marshaler_INOUT.BytesToCSharp(marshalBuffer_INOUT, ref INOUT);
    marshalBuffer_INOUT.Dispose();
    }
  }

  public void SetCurrentRange(double range, string channelList) {
    KtEL30000CppApiPINVOKE.KtEL30000OperationConstantCurrent_SetCurrentRange__SWIG_1(swigCPtr, range, channelList);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public KtEL30000OperationConstantCurrentProtection Protection() {
    global::System.IntPtr cPtr = KtEL30000CppApiPINVOKE.KtEL30000OperationConstantCurrent_Protection(swigCPtr);
    KtEL30000OperationConstantCurrentProtection ret = (cPtr == global::System.IntPtr.Zero) ? null : new KtEL30000OperationConstantCurrentProtection(cPtr, true);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public KtEL30000OperationConstantCurrentSlew Slew() {
    global::System.IntPtr cPtr = KtEL30000CppApiPINVOKE.KtEL30000OperationConstantCurrent_Slew(swigCPtr);
    KtEL30000OperationConstantCurrentSlew ret = (cPtr == global::System.IntPtr.Zero) ? null : new KtEL30000OperationConstantCurrentSlew(cPtr, true);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
