//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Keysight.KtEL30000.Bridge {
[System.CodeDom.Compiler.GeneratedCode("swig","3.0")]

internal class KtEL30000SystemTracing : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal KtEL30000SystemTracing(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(KtEL30000SystemTracing obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~KtEL30000SystemTracing() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          KtEL30000CppApiPINVOKE.delete_KtEL30000SystemTracing(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }


    public bool Enabled
    {
        get { return GetEnabled(); }
        set { SetEnabled(value); }
    }

    public string FileName
    {
        get { return GetFileName(); }
        set { SetFileName(value); }
    }

    public Keysight.KtEL30000.TracingLevel Level
    {
        get { return GetLevel(); }
        set { SetLevel(value); }
    }

  public void Flush() {
    KtEL30000CppApiPINVOKE.KtEL30000SystemTracing_Flush(swigCPtr);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Write(string message) {
    KtEL30000CppApiPINVOKE.KtEL30000SystemTracing_Write(swigCPtr, message);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool GetEnabled() {
    bool ret = KtEL30000CppApiPINVOKE.KtEL30000SystemTracing_GetEnabled(swigCPtr);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetEnabled(bool value) {
    KtEL30000CppApiPINVOKE.KtEL30000SystemTracing_SetEnabled(swigCPtr, value);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetFileName() {
    string ret = KtEL30000CppApiPINVOKE.KtEL30000SystemTracing_GetFileName(swigCPtr);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetFileName(string value) {
    KtEL30000CppApiPINVOKE.KtEL30000SystemTracing_SetFileName(swigCPtr, value);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public Keysight.KtEL30000.TracingLevel GetLevel() {
    Keysight.KtEL30000.TracingLevel ret = (Keysight.KtEL30000.TracingLevel)KtEL30000CppApiPINVOKE.KtEL30000SystemTracing_GetLevel(swigCPtr);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetLevel(Keysight.KtEL30000.TracingLevel value) {
    KtEL30000CppApiPINVOKE.KtEL30000SystemTracing_SetLevel(swigCPtr, (int)value);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
