//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Keysight.KtEL30000.Bridge {
[System.CodeDom.Compiler.GeneratedCode("swig","3.0")]

internal class KtEL30000StatusOperation : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal KtEL30000StatusOperation(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(KtEL30000StatusOperation obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~KtEL30000StatusOperation() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          KtEL30000CppApiPINVOKE.delete_KtEL30000StatusOperation(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }


    public Keysight.KtEL30000.StatusOperationFlags EnableRegister
    {
        get { return GetEnableRegister(); }
        set { SetEnableRegister(value); }
    }

    public Keysight.KtEL30000.StatusOperationFlags NegativeTransitionFilter
    {
        get { return GetNegativeTransitionFilter(); }
        set { SetNegativeTransitionFilter(value); }
    }

    public Keysight.KtEL30000.StatusOperationFlags PositiveTransitionFilter
    {
        get { return GetPositiveTransitionFilter(); }
        set { SetPositiveTransitionFilter(value); }
    }

  public Keysight.KtEL30000.StatusOperationFlags ReadConditionRegister() {
    Keysight.KtEL30000.StatusOperationFlags ret = (Keysight.KtEL30000.StatusOperationFlags)KtEL30000CppApiPINVOKE.KtEL30000StatusOperation_ReadConditionRegister(swigCPtr);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Keysight.KtEL30000.StatusOperationFlags ReadEventRegister() {
    Keysight.KtEL30000.StatusOperationFlags ret = (Keysight.KtEL30000.StatusOperationFlags)KtEL30000CppApiPINVOKE.KtEL30000StatusOperation_ReadEventRegister(swigCPtr);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Keysight.KtEL30000.StatusOperationFlags GetEnableRegister() {
    Keysight.KtEL30000.StatusOperationFlags ret = (Keysight.KtEL30000.StatusOperationFlags)KtEL30000CppApiPINVOKE.KtEL30000StatusOperation_GetEnableRegister(swigCPtr);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetEnableRegister(Keysight.KtEL30000.StatusOperationFlags value) {
    KtEL30000CppApiPINVOKE.KtEL30000StatusOperation_SetEnableRegister(swigCPtr, (int)value);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public Keysight.KtEL30000.StatusOperationFlags GetNegativeTransitionFilter() {
    Keysight.KtEL30000.StatusOperationFlags ret = (Keysight.KtEL30000.StatusOperationFlags)KtEL30000CppApiPINVOKE.KtEL30000StatusOperation_GetNegativeTransitionFilter(swigCPtr);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetNegativeTransitionFilter(Keysight.KtEL30000.StatusOperationFlags value) {
    KtEL30000CppApiPINVOKE.KtEL30000StatusOperation_SetNegativeTransitionFilter(swigCPtr, (int)value);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public Keysight.KtEL30000.StatusOperationFlags GetPositiveTransitionFilter() {
    Keysight.KtEL30000.StatusOperationFlags ret = (Keysight.KtEL30000.StatusOperationFlags)KtEL30000CppApiPINVOKE.KtEL30000StatusOperation_GetPositiveTransitionFilter(swigCPtr);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetPositiveTransitionFilter(Keysight.KtEL30000.StatusOperationFlags value) {
    KtEL30000CppApiPINVOKE.KtEL30000StatusOperation_SetPositiveTransitionFilter(swigCPtr, (int)value);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
