//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Keysight.KtEL30000.Bridge {
[System.CodeDom.Compiler.GeneratedCode("swig","3.0")]

internal class KtEL30000CppApi {
  public static readonly int USE_PINNING_FOR_BYTE_ARRAY_MARSHALING = KtEL30000CppApiPINVOKE.USE_PINNING_FOR_BYTE_ARRAY_MARSHALING_get();
}

}
