//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Keysight.KtEL30000.Bridge {
[System.CodeDom.Compiler.GeneratedCode("swig","3.0")]

internal class KtEvent : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal KtEvent(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(KtEvent obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~KtEvent() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          KtEL30000CppApiPINVOKE.delete_KtEvent(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

    // overloading +=, -= operator is not permitted in C#, But we can get the same effect by overloading +, - operator
    public static KtEvent operator + (KtEvent ins, KtEventHandler value)
    {
        return ins.addition_assign(value);
    }
    
    public static KtEvent operator - (KtEvent ins, KtEventHandler value)
    {
        return ins.subtraction_assign(value);
    }
    
    // Seems there is no way to overload operator() in C#...

  public KtEvent() : this(KtEL30000CppApiPINVOKE.new_KtEvent(), true) {
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public KtEvent addition_assign(KtEventHandler pHandlerToAdd) {
    KtEvent ret = new KtEvent(KtEL30000CppApiPINVOKE.KtEvent_addition_assign(swigCPtr, KtEventHandler.getCPtr(pHandlerToAdd)), false);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public KtEvent subtraction_assign(KtEventHandler pHandlerToRemove) {
    KtEvent ret = new KtEvent(KtEL30000CppApiPINVOKE.KtEvent_subtraction_assign(swigCPtr, KtEventHandler.getCPtr(pHandlerToRemove)), false);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void execute() {
    KtEL30000CppApiPINVOKE.KtEvent_execute(swigCPtr);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
