//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Keysight.KtEL30000.Bridge {
[System.CodeDom.Compiler.GeneratedCode("swig","3.0")]

internal class WarningKtEvent : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal WarningKtEvent(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(WarningKtEvent obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~WarningKtEvent() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          KtEL30000CppApiPINVOKE.delete_WarningKtEvent(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

        // overloading +=, -= operator is not permitted in C#, But we can get the same effect by overloading +, - operator
        public static WarningKtEvent operator + (WarningKtEvent ins,WarningKtEventHandler value)
        {
            return ins.addition_assign(value);
        }
    
        public static WarningKtEvent operator - (WarningKtEvent ins,WarningKtEventHandler value)
        {
            return ins.subtraction_assign(value);
        }
    
  public WarningKtEvent() : this(KtEL30000CppApiPINVOKE.new_WarningKtEvent(), true) {
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

  public WarningKtEvent addition_assign(WarningKtEventHandler pHandlerToAdd) {
    WarningKtEvent ret = new WarningKtEvent(KtEL30000CppApiPINVOKE.WarningKtEvent_addition_assign(swigCPtr, WarningKtEventHandler.getCPtr(pHandlerToAdd)), false);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public WarningKtEvent subtraction_assign(WarningKtEventHandler pHandlerToRemove) {
    WarningKtEvent ret = new WarningKtEvent(KtEL30000CppApiPINVOKE.WarningKtEvent_subtraction_assign(swigCPtr, WarningKtEventHandler.getCPtr(pHandlerToRemove)), false);
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void execute(IviWarningEventArgs args) {
    KtEL30000CppApiPINVOKE.WarningKtEvent_execute(swigCPtr, IviWarningEventArgs.getCPtr(args));
    if (KtEL30000CppApiPINVOKE.SWIGPendingException.Pending) throw KtEL30000CppApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
